### ISSUE TITLE
examples 

### ISSUE THREAD

**Issue by peymanmor** [Schlumberger/distpy#1]
I am not sure if I am missing something or the two strainrate2fbeConfig.json and plotsConfig.json are missing from the config_examples folder
thank you

**Comment by miwslb** [comment]
Thanks for trying **distpy** and for raising this issue to my attention.

You are correct, those files were missing from the config_examples folder. I have put them there so you should see them now. I also updated the example in the [disection of `CASE00.py`](https://github.com/Schlumberger/distpy/wiki/Reference-:-The-disection-of-CASE00.py) so that it aligns with the Noise Log generation example used elsewhere. The `strainrate2fbeConfig.json` and `plotsConfig.json` correspond to the examples in that Wiki page.
